### ISSUE TITLE
Custom parameters prefix support in snippet

### ISSUE THREAD

**Issue by Skejven** [Knotx/knotx-data-bridge#17]
Snippet parameters should enable defining HTML compliant prefixes, but when not necessary should be simplified.
See [knotx-core-419](https://github.com/Cognifide/knotx/pull/419) for more details.

**Comment by tomaszmichalak** [comment]
https://github.com/Knotx/knotx-data-bridge/pull/25

**Comment by tomaszmichalak** [comment]
Fixed.
