### ISSUE TITLE
README: how to implement my own adapter

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-data-bridge#29]
It can be a tutorial where we explain how to integrate with external datasource like database. This tutorial can be linked in README file. In the scope of this task:
- tutorial
- README update
- remove [Adapter maven archetype](https://github.com/Knotx/knotx-extension-archetype)

Please note that we need guide for both Gradle and Maven.

**Comment by Skejven** [comment]
outdated
