### ISSUE TITLE
Enable reading parameters from payload in HTTP action

### ISSUE THREAD

**Issue by Skejven** [Knotx/knotx-data-bridge#48]
**Describe the solution you'd like**
Currently, HTTP Action could send [parametrized service calls](https://github.com/Knotx/knotx-data-bridge/tree/master/http#parametrized-services-calls) using placeholders replacement with values from the HTTP request (query params, headers, etc.).
It could be very useful if the call could be also parametrized by the data from Fragment's `payload`. Example action configuration could look like this:

```hocon
actions {
  user-books {
    factory = http
    config {
      endpointOptions {
        path = /api/user-books/{payload.user.userId}
        domain = localhost
        port = 3000
        allowedRequestHeaders = ["Content-Type"]
      }
    }
  }
}
```

**Additional context**
Consider extending [Knot.x Server Commons](https://github.com/Knotx/knotx-server-http/tree/master/common/placeholders) and implement a substitutor that can extract the value from JsonObject. Some of the logic is already implemented in the [PayloadToBodyActionFactory](https://github.com/Knotx/knotx-fragments-handler/blob/master/core/src/main/java/io/knotx/fragments/handler/action/PayloadToBodyActionFactory.java#L61). Maybe it could be extracted to commons and re-used?

**Comment by tomaszmichalak** [comment]
@marcinkp what is the status of this task?

**Comment by Skejven** [comment]
This was done in #51 and #52.
